config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :portfolios, except: [:show]
  get 'angular-item', to: 'portfolios#angular'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'

  resources :blogs do 
  	member do
  		get :toggle_status
  	end
  end

  root to: 'pages#home'
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  include Placeholder

  after_initialize :set_defaults

  has_many :technologies
  accepts_nested_attributes_for :technologies, 
                                reject_if: lambda { |attrs| attrs['name'].blank? }

  validates_presence_of :title, :body, :main_image, :thumb_image

  scope :ruby_on_rails, -> { where(subtitle: 'Ruby on rails') }

  def self.angular
    where(subtitle: 'Angular JS')
  end

  def set_defaults
    self.main_image ||= Placeholder.image_generator(height: '600', width: '400')
    self.thumb_image ||= Placeholder.image_generator(height: '350', width: '200')
  end

  def self.by_position
    order("position ASC") 
  end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  layout "portfolio"
  access all: [:show, :index, :angular], user: {except: [:destroy, :new, :create, :edit, :update]}, site_admin: :all
  
  def index
    @portfolio_items = Portfolio.by_position
  end

  def angular
    @angular_portfolio_items = Portfolio.angular
  end

  def new
    @portfolio_item = Portfolio.new
    3.times { @portfolio_item.technologies.build }
  end

  def create
    @portfolio_item = Portfolio.new(portfolio_params)

    respond_to do |format|
      if @portfolio_item.save
        format.html { redirect_to portfolios_path, notice: 'Portfolio was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def edit
    @portfolio_item = Portfolio.find(params[:id])
  end

  def update
    @portfolio_item = Portfolio.find(params[:id])

    respond_to do |format|
      if @portfolio_item.update(portfolio_params)
        format.html { redirect_to portfolios_path, notice: 'Portfolio was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def show
    @portfolio_item = Portfolio.find(params[:id])
  end

  def destroy
    @portfolio_item = Portfolio.find(params[:id])

    @portfolio_item.destroy
    respond_to do |format|
      format.html { redirect_to portfolios_url, notice: 'Record was successfully destroyed.' }
    end
  end

  private

  def portfolio_params
    params.require(:portfolio).permit(
      :title, 
      :subtitle, 
      :body, 
      technologies_attributes: [:name]
    )
  end
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/portfolios/_form.html.erb
<%= form_for(@portfolio_item) do |form| %>
  <div class= 'row'>
    <div class='col-md-6'>
      <div class="form-group">
        <%= form.label :title %>
        <%= form.text_field :title, id: :blog_title, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label :subtitle %>
        <%= form.text_field :subtitle, id: :blog_subtitle, class: 'form-control' %>
      </div>
    </div>

    <div class='col-md-6'>
      <div class="form-group">
        <%= form.label :body %>
        <%= form.text_area :body, id: :blog_body, class: 'form-control', rows: 13 %>
      </div>
    </div>
  </div>
   
  <div class='col-md-12'>
    <h2>Technologies Used:</h2>
    <div>
      <%= form.fields_for :technologies do |technology_form| %>
        <div class="form-group">
          <%= technology_form.label :name %>
          <%= technology_form.text_field :name, class: 'form-control' %>
        </div>
      <% end %>
    </div>

    <div class="form-group">
      <%= form.submit 'Save Portfolio Item', class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/portfolios/_portfolio_item.html.erb
<div class="col-md-4">
  <div class="card mb-4 shadow-sm">
    <%= image_tag portfolio_item.thumb_image unless portfolio_item.thumb_image.nil? %>
    <div class="card-body">
      <p class="card-text">
      	<span><%= link_to portfolio_item.title, portfolio_show_path(portfolio_item) %></span>	<%= portfolio_item.subtitle %>
      </p>
      <div class="d-flex justify-content-between align-items-center">
        <div class="btn-group">
          <%= link_to "View", portfolio_show_path(portfolio_item), class: 'btn btn-sm btn-outline-secondary' %>
          <%= link_to "Edit", edit_portfolio_path(portfolio_item), class: 'btn btn-sm btn-outline-secondary' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/portfolios/angular.html.erb
<h1>Angular Portfolio Items</h1>

<%= link_to "Create New Item", new_portfolio_path if logged_in?(:site_admin) %>

<%= @angular_portfolio_items.each do |portfolio_item| %>
	<p><%= link_to portfolio_item.title, portfolio_show_path(portfolio_item) %></p>
	<p><%= portfolio_item.subtitle %></p>
	<p><%= portfolio_item.body %></p>
	<%= image_tag portfolio_item.thumb_image unless portfolio_item.thumb_image.nil? %>
	<%= link_to "Edit", edit_portfolio_path(portfolio_item) %>
	<%= link_to 'Delete Portfolio Item', portfolio_path(portfolio_item), method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>

app/views/portfolios/edit.html.erb
<div class='container portfolio-form'>
	<h1>Edit Portfolio Item</h1>
	<%= render 'form', portfolio_item: @portfolio_item %>
</div>

app/views/portfolios/index.html.erb
<div class="album py-5 bg-light">
  <div class="container">
    <div class="row">
			<%= render partial: 'portfolio_item', collection: @portfolio_items %>
		</div>
	</div>
</div>

app/views/portfolios/new.html.erb
<div class='container portfolio-form'>
	<h1>Create a new Portfolio Item</h1>

	<%= render 'form', portfolio_item: @portfolio_item %>
</div>

app/views/portfolios/show.html.erb
<div class='container'>
	<div class='row'>
		<div class='col-md-7'>
			<%= image_tag @portfolio_item.main_image %>
		</div>
		<div class='col-md-5'>
			<h1><%= @portfolio_item.title %></h1>

			<hr>

			<em><%= @portfolio_item.subtitle %></em>

			<p><%= @portfolio_item.body %></p>

			<h3>Technologies Used:</h3>

			<% @portfolio_item.technologies.each do |t| %>
				<p><%= t.name %></p>
			<% end %>
		</div>		
	</div>
</div>