config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :portfolios, except: [:show]
  get 'angular-item', to: 'portfolios#angular'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'

  resources :blogs do 
  	member do
  		get :toggle_status
  	end
  end

  root to: 'pages#home'
end

app/views/shared/_application_footer.html.erb
<footer class="mastfoot mt-auto">
  <div class="inner">
    <p><%= copyright_generator %></p>
  </div>
</footer>

app/views/shared/_application_nav.html.erb
<header class="masthead mb-auto">
	<div class="inner">
	  <h3 class="masthead-brand">Erica Bista</h3>
	  <nav class="nav nav-masthead justify-content-center app-nav">
	    <%= nav_helper 'nav-link', 'span' %>
	    <%= login_helper 'nav-link'%>
	  </nav>
	</div>
</header>

app/views/shared/_blog_footer.html.erb
<footer class="blog-footer">
  <p><%= copyright_generator %></p>
  <p>
    <a href="#">Back to top</a>
  </p>
</footer>

app/views/shared/_blog_masthead.html.erb
<div class="blog-header">
  <div class="container">
    <h1 class="blog-title">My Blog</h1>
    <p class="lead blog-description">An example blog template built with Bootstrap.</p>
    <%= link_to 'Write a New Blog', new_blog_path if logged_in?(:site_admin) %>
  </div>
</div>

app/views/shared/_blog_nav.html.erb
<div class="blog-masthead">
  <div class="container">
    <nav class="nav blog-nav">
      <%= nav_helper 'nav-link', 'span' %>
      <%= login_helper 'nav-link' %>
    </nav>
  </div>
</div>

app/views/shared/_blog_sidebar.html.erb
<div class="col-sm-3 offset-sm-1 blog-sidebar">
  <div class="sidebar-module sidebar-module-inset">
    <h4>About</h4>
    <p>Erica Bista <em>Senior Analyst Programmer</em> at Unisversity of Sydney. Skilled in development of products as full stack Ruby on Rails with four years of commercial development experience. Enjoy working in a team forming strong relationships, and able to work under pressure whole delivering high quality work.</p>
  </div>
  

  <div class="sidebar-module">
    <h4>Elsewhere</h4>
    <ol class="list-unstyled social-links">
      <li><%=link_to fa_icon("github")%></li>
      <li><%=link_to fa_icon("instagram")%></li>
      <li><%=link_to fa_icon("facebook")%></li>
    </ol>
  </div>
</div>

app/views/shared/_nav.html.erb
<div class="<%= location %>">
  <div><%= nav_helper 'nav-link', 'span' %></div>
</div>

app/views/shared/_portfolio_footer.html.erb
<footer class="text-muted">
  <div class="container">
    <p class="float-right">
    	<%= link_to 'View All Portfolio Items', portfolios_path %> |
      <a href="#">Back to top</a>
    </p>
    <p><%= copyright_generator %></p>
  </div>
</footer>

app/views/shared/_portfolio_masthead.html.erb
<section class="jumbotron text-center">
  <div class="container">
    <h1 class="jumbotron-heading">My Portfolio</h1>
    <p class="lead text-muted">Something short and leading about the collection below—its contents, the creator, etc. Make it short and sweet, but not too short so folks don’t simply skip over it entirely.</p>
    <p>
      <%= link_to 'Find Out More About Me', about_me_path, class: 'btn btn-primary' %>
      <%= link_to 'My Blogs', blogs_path, class: 'btn btn-secondary' %>
    </p>
  </div>
</section>

app/views/shared/_portfolio_nav.html.erb
<div class="collapse bg-dark" id="navbarHeader">
  <div class="container">
    <div class="row">
      <div class="col-sm-8 col-md-7 py-4">
        <h4 class="text-white">About</h4>
        <p class="text-muted">Add some information about the album below, the author, or any other background context. Make it a few sentences long so folks can pick up some informative tidbits. Then, link them off to some social networking sites or contact information.</p>
      </div>
      <div class="col-sm-4 offset-md-1 py-4">
        <h4 class="text-white">Explore</h4>
        <ul class="list-unstyled">
          <%= nav_helper 'nav-link', 'span' %>
        </ul>
      </div>
    </div>
  </div>
</div>

<div class="navbar navbar-dark bg-dark shadow-sm">
  <div class="container d-flex justify-content-between">
    <a href="#" class="navbar-brand d-flex align-items-center">
      <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="mr-2" viewBox="0 0 24 24" focusable="false"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/><circle cx="12" cy="13" r="4"/></svg>
      <strong>Erica Bista</strong>
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </div>
</div>